application: tmdbsearchljma
version: 1
runtime: python
api_version: 1

handlers:
- url: /images(.*\.(gif|png|jpg|ico|js|css))
  static_files: \
  upload: (.*\.(gif|png|jpg|ico|js|css))
  
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
